from django.core.exceptions import ValidationError

def validate_edu_email(value):
  pass